"""
Generate a complete test output showing EditorCode component conversion
"""
import sys
import os
import asyncio

sys.path.insert(0, os.path.dirname(__file__))

from section_processor import SectionContentProcessor

async def generate_test_output():
    """Generate test output with EditorCode examples"""
    processor = SectionContentProcessor(output_dir="test_output")
    
    section_data = {
        "id": "editor_code_test",
        "title": "EditorCode Component Test",
        "components": [
            {
                "type": "SlateHTML",
                "content": {
                    "html": "<h2>EditorCode Component Examples</h2><p>This section demonstrates the EditorCode component conversion to LaTeX.</p>"
                }
            },
            {
                "type": "SlateHTML",
                "content": {
                    "html": "<h3>Example 1: JavaScript Function</h3>"
                }
            },
            {
                "type": "EditorCode",
                "mode": "edit",
                "content": {
                    "language": "javascript",
                    "content": "deliverContent(origin_id, server_list, content_type, content_version, description)",
                    "version": "1.0",
                    "comp_id": "vWL41yBruScOCv_RqiKcL"
                }
            },
            {
                "type": "SlateHTML",
                "content": {
                    "html": "<h3>Example 2: Python Class</h3>"
                }
            },
            {
                "type": "EditorCode",
                "mode": "edit",
                "content": {
                    "language": "python",
                    "content": "class DataProcessor:\n    def __init__(self, data):\n        self.data = data\n    \n    def process(self):\n        return [item.upper() for item in self.data]",
                    "version": "1.0"
                }
            },
            {
                "type": "SlateHTML",
                "content": {
                    "html": "<h3>Example 3: SQL Query</h3>"
                }
            },
            {
                "type": "EditorCode",
                "mode": "view",
                "content": {
                    "language": "sql",
                    "content": "SELECT u.name, COUNT(o.id) as order_count\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nGROUP BY u.name\nORDER BY order_count DESC;",
                    "version": "1.0"
                }
            },
            {
                "type": "SlateHTML",
                "content": {
                    "html": "<h3>Example 4: C++ Code</h3>"
                }
            },
            {
                "type": "EditorCode",
                "mode": "edit",
                "content": {
                    "language": "cpp",
                    "content": "#include <iostream>\nusing namespace std;\n\nint main() {\n    cout << \"Hello, World!\" << endl;\n    return 0;\n}",
                    "version": "1.0"
                }
            }
        ]
    }
    
    print("Generating EditorCode test output...")
    
    latex_content, images, component_types = await processor.process_section_components_async(section_data)
    
    # Write to output file
    output_file = "test_editor_code_output.tex"
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("% EditorCode Component Test Output\n")
        f.write("% Generated by test_editor_code_output.py\n\n")
        f.write(latex_content)
    
    print(f"✅ Test output written to: {output_file}")
    print(f"\nComponent types processed: {', '.join(component_types)}")
    print(f"Total LaTeX lines: {len(latex_content.splitlines())}")

if __name__ == "__main__":
    asyncio.run(generate_test_output())
